fix(firewall-cmd): don't shadow config import
$ flake8-3.13
./src/firewall-cmd.in:1609:9: F811 redefinition of unused 'config' from line 29

Fixes: 2a44221c6be5 ("fix(firewall-cmd): use config.VERSION for --version")